In [1]:
!pip install opencv-python

In [2]:
import cv2

Reading Image as Color or GrayScale Image in Python using OpenCV
In this article, we’ll try to open an image by using OpenCV (Open Source Computer Vision). To use the OpenCV library in python, we need to install these libraries as a prerequisite:

Numpy Library (Necessary, because OpenCV uses it in the background).
OpenCV python
To install these libraries, we need to run these pip commands in cmd:

pip install opencv-python
pip install numpy
pip install matplotlib
Functions you need to understand
Read an image from file (using cv::imread)
Display an image in an OpenCV window (using cv::imshow)
Write an image to a file (using cv::imwrite)

Reading a GrayScale Image in Python using OpenCV

In [1]:
import cv2
img = cv2.imread('D:\\man.jpeg',cv2.IMREAD_GRAYSCALE)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
#same as above 
import cv2
img = cv2.imread('D:\\man.jpeg',0)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Reading a Color Image in Python using OpenCV

In [3]:
import cv2
img = cv2.imread('D:\\man.jpeg',cv2.IMREAD_COLOR)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
#or
import cv2
img = cv2.imread('D:\\man.jpeg',1)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
import matplotlib.pyplot as plt

Get RGB Value of a Single Pixel

In [6]:
img[100,100]

array([237, 236, 240], dtype=uint8)

In [7]:
B,G,R = img[100,100]
print(B,G,R)

237 236 240


In [8]:
print('Type of the image : ' , type(img))
print()
print('Shape of the image : {}'.format(img.shape))
print('Image Height {}'.format(img.shape[0]))
print('Image Width {}'.format(img.shape[1]))
print('Dimension of Image {}'.format(img.ndim))

Type of the image :  <class 'numpy.ndarray'>

Shape of the image : (531, 413, 3)
Image Height 531
Image Width 413
Dimension of Image 3


Read Image from Height 100-200 Pixel and Width 200-400 Pixel

In [9]:
import cv2
img=cv2.imread('D:\\man.jpeg',1)
#roi=region of intrest
roi=img[100:200,200:400]
cv2.imshow('image',roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

Resize image to 200px 180px ( Width Height )
RESIZEING IMAGE 

In [10]:
import cv2
img = cv2.imread('D:\\man.jpeg',1)
resize=cv2.resize(img,(200,180))
cv2.imshow('image',resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Rotating the Image
There are a lot of steps involved in rotating an image. The 2 main functions used here are –

getRotationMatrix2D()
warpAffine()
getRotationMatrix2D() : It takes 3 arguments

center – The center coordinates of the image
Angle – The angle (in degrees) by which the image should be rotated
Scale – The scaling factor
warpAffine()

The function warpAffine transforms the source image using the rotation matrix:

In [13]:
import cv2
img = cv2.imread('D:\\man.jpeg',1)

h,w = img.shape[:2]
center = (w // 2, h // 2) 
matrix = cv2.getRotationMatrix2D(center, 135, 0.5)  
rotated = cv2.warpAffine(img, matrix, (w, h)) 

cv2.imshow('image',rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

Drawing a Rectangle on Image in Python using OpenCV
Drawing a Rectangle
rectangle() function take 5 Arguments

Image
Top-left corner co-ordinates
Bottom-right corner co-ordinates
Color (in BGR format)
Line width

In [10]:
import cv2
img = cv2.imread('D:\\man.jpeg',1)

output = img.copy() 
rectangle = cv2.rectangle(output, (100, 20),(300, 300), (0, 255, 0), 5) 
cv2.imshow('image',rectangle)
cv2.waitKey(0)
cv2.destroyAllWindows()

Displaying text on Image in Python using OpenCV
putText() Function takes in 7 arguments –

Image
Text to be displayed
Bottom-left corner co-ordinates, from where the text should start
Font
Font size
Color (BGR format)
Line width

In [14]:
import cv2
img = cv2.imread('D:\\man.jpeg',1)

output = img.copy() 
text = cv2.putText(output, 'LAKSHMI MANI SHANKAR', (120, 25),  cv2.FONT_HERSHEY_SIMPLEX, 0.6, (60, 60, 60), 2)
cv2.imshow('image',text)
cv2.waitKey(0)
cv2.destroyAllWindows()

Visualizing the Different Color Channels of an RGB Image in Python using OpenCV

In [16]:
import cv2
img = cv2.imread('D:\\op.png',1)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
import cv2 
img=cv2.imread('D:\\op.png',1)
B,G,R = cv2.split(img) 
print(B)
print(G)
print(R)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [19]:
cv2.imshow("blue", B) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [20]:
cv2.imshow("Green", G) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [21]:
cv2.imshow("red", R) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

Arithmetic Operations on Images using OpenCV
Arithmetic Operations like Addition, Subtraction, and Bitwise Operations(AND, OR, NOT, XOR) can be applied to the input images

Addition
Subtraction
Bitwise operations are used in image manipulation and used for extracting essential parts in the image. In this article, Bitwise operations used are:

Bitwise AND
Bitwise OR
Bitwise XOR
Bitwise NOT
1. Addition
Syntax: cv2.add(img1, img2)
But adding the pixels is not an ideal situation. So, we use cv2.addweighted(). Remember, both images should be of equal size and depth.

In [25]:
import cv2  
import numpy as np  
     
image1 = cv2.imread('D:\\i1.jpg',1)  
image2 = cv2.imread('D:\\i2.jpg',1) 
  
weightedSum = cv2.add(image1,image2) 

cv2.imshow('Image', weightedSum) 
  
cv2.waitKey(0)
cv2.destroyAllWindows()

2.Subtraction of Image:
Just like addition, we can subtract the pixel values in two images and merge them with the help of cv2.subtract(). The images should be of equal size and depth.

Syntax: cv2.subtract(image1, image2)

In [26]:
import cv2  
import numpy as np  
     
image1 = cv2.imread('D:\\i1.jpg',1)  
image2 = cv2.imread('D:\\i2.jpg',1) 
  
weightedSum = cv2.subtract(image1,image2) 

cv2.imshow('Image', weightedSum) 
  
cv2.waitKey(0)
cv2.destroyAllWindows()

Access Camera Using OpenCV with Python
first, we Import libraries OpenCV.
Then we use VideoCapture(0) function to capture the feed of the webcam, here 0 indicates the default value of webcam. If you have secondary webcam use 1 instead of 0
Now read the frame of the camera frame by frame
ret is a boolean variable that checks if the camera is on or not
the frame is a variable in which all the camera feed is being saved

In [ ]:
import cv2
capture=cv2.VideoCapture(0)
while True:
    ret,frame=capture.read()
    cv2.imshow('Color',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
capture.release()
cv2.destroyAllWindows()S

Save Image from Webcam

In [3]:
import cv2
capture=cv2.VideoCapture(0)
while True:
    ret,frame=capture.read()
    cv2.imshow('Color',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.imwrite("MachineLearning.jpg",frame)
        break
capture.release()
cv2.destroyAllWindows()

Record Video From a Webcam using OpenCV
cv2.VideoWriter( filename, fourcc, fps, frameSize )
The parameters are :

filename: Specifies the name of the output video file.
fourcc: (for recording) Defining the codec
fps: Defined frame rate of the output video stream
frameSize: Size of the video frame

In [5]:
import cv2
capture=cv2.VideoCapture(0)

cod = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('out.avi',cod,20.0,(640,480))

while True:
    ret,frame=capture.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Gray',gray)
    cv2.imshow('Color',frame)
    out.write(frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
capture.release()
cv2.destroyAllWindows()